/**
 * ─── DEV MOCK DATA ───────────────────────────────────────────────────────────
 * Used ONLY in local dev (non-Telegram browser runs) so you can iterate on UI
 * without a running backend. Nothing here is ever imported in production paths.
 */

export const DEV_USER = {
    id: 'dev-user',
    telegram_id: 12345,
    username: 'dev_user',
    first_name: 'Developer',
    photo_url: null as string | null,
    wallet_address: '0xDEV0000000000000000000000000000000ABCDEF',
    wallet_type: 'bot' as 'bot' | 'external',
    upi_id: 'devuser@upi',
    phone_number: '9876543210',
    bank_account_number: '1234567890',
    bank_ifsc: 'SBIN0001234',
    bank_name: 'SBI',
    digital_rupee_id: null as string | null,
    receive_address: null as string | null,
    cdm_bank_number: null as string | null,
    cdm_bank_name: null as string | null,
    cdm_phone: null as string | null,
    cdm_user_name: null as string | null,
    trade_count: 48,
    completed_trades: 45,
    trust_score: 97,
    points: 1240.5,
    tier: 'gold',
    is_verified: true,
    is_admin: false,
    created_at: '2024-06-15T10:30:00Z',
};

// ─── Home page: ads (sell orders for "buy" tab, buy orders for "sell" tab) ───
export const DEMO_ORDERS = [
    {
        id: 'demo-order-1',
        type: 'sell',
        user_id: 'trader-1',
        username: 'CryptoKing_KL',
        first_name: 'Arjun',
        photo_url: null,
        token: 'USDC',
        chain: 'base',
        amount: 500,
        filled_amount: 0,
        rate: 87.50,
        payment_methods: ['UPI', 'IMPS'],
        completed_trades: 312,
        trust_score: 99,
        created_at: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-order-2',
        type: 'sell',
        user_id: 'trader-2',
        username: 'P2PVipin',
        first_name: 'Vipin',
        photo_url: null,
        token: 'USDC',
        chain: 'bsc',
        amount: 1000,
        filled_amount: 200,
        rate: 87.20,
        payment_methods: ['IMPS', 'BANK'],
        completed_trades: 98,
        trust_score: 94,
        created_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-order-3',
        type: 'sell',
        user_id: 'trader-3',
        username: 'SarahTrades',
        first_name: 'Sarah',
        photo_url: null,
        token: 'USDC',
        chain: 'base',
        amount: 250,
        filled_amount: 50,
        rate: 87.80,
        payment_methods: ['UPI'],
        completed_trades: 56,
        trust_score: 91,
        created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-order-4',
        type: 'buy',
        user_id: 'trader-4',
        username: 'RohanFi',
        first_name: 'Rohan',
        photo_url: null,
        token: 'USDC',
        chain: 'bsc',
        amount: 750,
        filled_amount: 0,
        rate: 86.90,
        payment_methods: ['UPI', 'BANK'],
        completed_trades: 201,
        trust_score: 98,
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-order-5',
        type: 'sell',
        user_id: 'trader-5',
        username: 'KeralaHODL',
        first_name: 'Priya',
        photo_url: null,
        token: 'USDT',
        chain: 'bsc',
        amount: 300,
        filled_amount: 0,
        rate: 87.10,
        payment_methods: ['IMPS', 'UPI'],
        completed_trades: 143,
        trust_score: 96,
        created_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-order-6',
        type: 'sell',
        user_id: 'trader-6',
        username: 'AmalDEFI',
        first_name: 'Amal',
        photo_url: null,
        token: 'USDT',
        chain: 'base',
        amount: 2000,
        filled_amount: 500,
        rate: 87.30,
        payment_methods: ['BANK', 'IMPS'],
        completed_trades: 427,
        trust_score: 99,
        created_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-order-7',
        type: 'buy',
        user_id: 'trader-7',
        username: 'NeethuBTC',
        first_name: 'Neethu',
        photo_url: null,
        token: 'USDT',
        chain: 'bsc',
        amount: 400,
        filled_amount: 0,
        rate: 86.70,
        payment_methods: ['UPI'],
        completed_trades: 67,
        trust_score: 90,
        created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
];

// ─── Trader Profiles: Mock data for clinical profile cards ────────────────────
export const DEMO_PROFILES: Record<string, any> = {
    'trader-1': {
        id: 'trader-1',
        username: 'CryptoKing_KL',
        first_name: 'Arjun',
        photo_url: null,
        completed_trades: 312,
        buy_count: 145,
        sell_count: 167,
        total_volume: 45200.50,
        completion_rate: 99,
        level: 5,
        member_since: '2023-01-15T12:00:00Z',
        bio: 'Professional P2P trader from Kochi. Fast release, 24/7 active for bulk orders. 🛡️',
        instagram_handle: 'arjun_crypto',
        x_handle: 'arjun_p2p'
    },
    'trader-2': {
        id: 'trader-2',
        username: 'P2PVipin',
        first_name: 'Vipin',
        photo_url: null,
        completed_trades: 98,
        buy_count: 40,
        sell_count: 58,
        total_volume: 12400.00,
        completion_rate: 94,
        level: 3,
        member_since: '2023-11-20T10:30:00Z',
        bio: 'Trusted regional dealer. I prefer UPI/IMPS. Respect and honesty first. 🙏',
        instagram_handle: 'vipin_kerala',
        x_handle: null
    },
    'trader-3': {
        id: 'trader-3',
        username: 'SarahTrades',
        first_name: 'Sarah',
        photo_url: null,
        completed_trades: 56,
        buy_count: 30,
        sell_count: 26,
        total_volume: 8900.25,
        completion_rate: 91,
        level: 2,
        member_since: '2024-02-10T09:15:00Z',
        bio: 'Casual trader. Small amounts only. Fast verification! ✨',
        instagram_handle: null,
        x_handle: 'sarah_crypto_in'
    },
    'trader-4': {
        id: 'trader-4',
        username: 'RohanFi',
        first_name: 'Rohan',
        photo_url: null,
        completed_trades: 201,
        buy_count: 110,
        sell_count: 91,
        total_volume: 25400.00,
        completion_rate: 98,
        level: 4,
        member_since: '2023-05-12T14:30:00Z',
        bio: 'Active trader on both networks. ⚡ Quick response guaranteed.',
        instagram_handle: 'rohan_fi',
        x_handle: 'rohan_trades'
    },
    'trader-5': {
        id: 'trader-5',
        username: 'KeralaHODL',
        first_name: 'Priya',
        photo_url: null,
        completed_trades: 143,
        buy_count: 65,
        sell_count: 78,
        total_volume: 18200.00,
        completion_rate: 96,
        level: 3,
        member_since: '2023-08-01T11:00:00Z',
        bio: 'Kerala based. UPI only. Quick release and secure transactions. 🤝',
        instagram_handle: 'kerala_hodl',
        x_handle: null
    },
    'trader-6': {
        id: 'trader-6',
        username: 'AmalDEFI',
        first_name: 'Amal',
        photo_url: null,
        completed_trades: 427,
        buy_count: 210,
        sell_count: 217,
        total_volume: 68500.00,
        completion_rate: 99,
        level: 5,
        member_since: '2022-12-10T08:00:00Z',
        bio: 'Defi expert, bulk trades welcome. 24x7 active. 🚀',
        instagram_handle: null,
        x_handle: 'amal_defi'
    },
    'trader-7': {
        id: 'trader-7',
        username: 'NeethuBTC',
        first_name: 'Neethu',
        photo_url: null,
        completed_trades: 67,
        buy_count: 32,
        sell_count: 35,
        total_volume: 10100.00,
        completion_rate: 90,
        level: 2,
        member_since: '2024-03-01T15:00:00Z',
        bio: 'Bitcoin and stablecoin trader. Safe and quick. 🌟',
        instagram_handle: 'neethu_btc',
        x_handle: null
    }
};


// ─── Orders page: trade history ───────────────────────────────────────────────
export const DEMO_TRADES = [
    {
        id: 'demo-trade-1',
        buyer_id: 'dev-user',
        seller_id: 'trader-1',
        buyer_username: 'dev_user',
        seller_username: 'CryptoKing_KL',
        buyer_first_name: 'Developer',
        seller_first_name: 'Arjun',
        seller_photo_url: null,
        buyer_photo_url: null,
        token: 'USDC',
        chain: 'base',
        amount: 100,
        rate: 87.50,
        status: 'in_escrow',
        created_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-trade-2',
        buyer_id: 'trader-2',
        seller_id: 'dev-user',
        buyer_username: 'P2PVipin',
        seller_username: 'dev_user',
        buyer_first_name: 'Vipin',
        seller_first_name: 'Developer',
        buyer_photo_url: null,
        seller_photo_url: null,
        token: 'USDC',
        chain: 'bsc',
        amount: 200,
        rate: 87.20,
        status: 'fiat_sent',
        created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-trade-3',
        buyer_id: 'dev-user',
        seller_id: 'trader-3',
        buyer_username: 'dev_user',
        seller_username: 'SarahTrades',
        buyer_first_name: 'Developer',
        seller_first_name: 'Sarah',
        seller_photo_url: null,
        buyer_photo_url: null,
        token: 'USDT',
        chain: 'base',
        amount: 150,
        rate: 87.10,
        status: 'completed',
        created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-trade-4',
        buyer_id: 'trader-4',
        seller_id: 'dev-user',
        buyer_username: 'RohanFi',
        seller_username: 'dev_user',
        buyer_first_name: 'Rohan',
        seller_first_name: 'Developer',
        buyer_photo_url: null,
        seller_photo_url: null,
        token: 'USDC',
        chain: 'bsc',
        amount: 500,
        rate: 86.90,
        status: 'completed',
        created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-trade-5',
        buyer_id: 'dev-user',
        seller_id: 'trader-5',
        buyer_username: 'dev_user',
        seller_username: 'KeralaHODL',
        buyer_first_name: 'Developer',
        seller_first_name: 'Priya',
        seller_photo_url: null,
        buyer_photo_url: null,
        token: 'USDT',
        chain: 'bsc',
        amount: 75,
        rate: 87.30,
        status: 'refunded',
        created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
        id: 'demo-trade-6',
        buyer_id: 'dev-user',
        seller_id: 'trader-6',
        buyer_username: 'dev_user',
        seller_username: 'AmalDEFI',
        buyer_first_name: 'Developer',
        seller_first_name: 'Amal',
        seller_photo_url: null,
        buyer_photo_url: null,
        token: 'USDC',
        chain: 'base',
        amount: 300,
        rate: 87.50,
        status: 'disputed',
        created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    },
];
